package Vista;

import Controlador.*;
import java.awt.event.ActionEvent;
import javax.swing.*;

public class MenuPrincial extends javax.swing.JFrame {
	
  public MenuPrincial() {
        initComponents();
				this.setLocationRelativeTo(null);
				groupButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jButtonNuevaSolicitud = new javax.swing.JButton();
    jButtonConsultarStock = new javax.swing.JButton();
    jButtonSolicitudesPendientes = new javax.swing.JButton();
    jRadioButtonSucursal1 = new javax.swing.JRadioButton();
    jRadioButtonSucursal2 = new javax.swing.JRadioButton();
    jLabel2 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
    jLabel1.setText("Menú Principal");

    jButtonNuevaSolicitud.setText("Nueva Solicitud");
    jButtonNuevaSolicitud.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonNuevaSolicitudActionPerformed(evt);
      }
    });

    jButtonConsultarStock.setText("Stock");
    jButtonConsultarStock.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonConsultarStockActionPerformed(evt);
      }
    });

    jButtonSolicitudesPendientes.setText("Solicitudes Pendientes");
    jButtonSolicitudesPendientes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonSolicitudesPendientesActionPerformed(evt);
      }
    });

    jRadioButtonSucursal1.setText("San Miguel");
    jRadioButtonSucursal1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButtonSucursal1ActionPerformed(evt);
      }
    });

    jRadioButtonSucursal2.setText("Yerba Buena");
    jRadioButtonSucursal2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jRadioButtonSucursal2ActionPerformed(evt);
      }
    });

    jLabel2.setText("Sucursal:");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
        .addComponent(jButtonSolicitudesPendientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jButtonConsultarStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jButtonNuevaSolicitud, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
          .addContainerGap()
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
              .addComponent(jRadioButtonSucursal1)
              .addGap(18, 18, 18)
              .addComponent(jRadioButtonSucursal2))
            .addComponent(jLabel2))))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jRadioButtonSucursal1)
          .addComponent(jRadioButtonSucursal2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButtonNuevaSolicitud)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButtonConsultarStock)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButtonSolicitudesPendientes)
        .addGap(46, 46, 46))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevaSolicitudActionPerformed(java.awt.event.ActionEvent evt) {                                                      
			ControladorNuevaSolicitud.crearSolicitud(this, rootPaneCheckingEnabled);
      //vistaNuevaSolicitud.setVisible(rootPaneCheckingEnabled);
    }

    private void jButtonConsultarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarStockActionPerformed
      ControladorConsultarStock.consultarStock(this, rootPaneCheckingEnabled);
    }//GEN-LAST:event_jButtonConsultarStockActionPerformed

  private void jButtonSolicitudesPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    ControladorSolicitudesPendientes.MostrarSolicitudes(this, rootPaneCheckingEnabled);
  }//GEN-LAST:event_jButton3ActionPerformed

  private void jRadioButtonSucursal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSucursal1ActionPerformed
    Main.setSucursalActual(jRadioButtonSucursal1.getText());
    System.out.println(Main.getSucursalActual());
  }//GEN-LAST:event_jRadioButtonSucursal1ActionPerformed

  private void jRadioButtonSucursal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSucursal2ActionPerformed
    Main.setSucursalActual(jRadioButtonSucursal2.getText());
    System.out.println(Main.getSucursalActual());
  }//GEN-LAST:event_jRadioButtonSucursal2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincial().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonConsultarStock;
  private javax.swing.JButton jButtonNuevaSolicitud;
  private javax.swing.JButton jButtonSolicitudesPendientes;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JRadioButton jRadioButtonSucursal1;
  private javax.swing.JRadioButton jRadioButtonSucursal2;
  // End of variables declaration//GEN-END:variables

	private void groupButton() {
		ButtonGroup grupoBotonesSucursal = new ButtonGroup();
		grupoBotonesSucursal.add(jRadioButtonSucursal1);
		grupoBotonesSucursal.add(jRadioButtonSucursal2);
	}
}
