package Vista;

import Modelo.Catalogo;
import Modelo.Color;
import Modelo.LineaDeSolicitud;
import Modelo.Prenda;
import Modelo.Solicitud;
import Modelo.Talle;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pequege
 */
public class VistaNuevoFormulario extends javax.swing.JFrame {

    /**
     * Creates new form VistaNuevoFormulario
     */
    public Catalogo catalogo = new Catalogo();
    ArrayList<LineaDeSolicitud> lineasDeSolicitud = new ArrayList<>();
    
    public VistaNuevoFormulario() {
        initComponents();
        limpiarListaDeSolicitudes();
        llenarComboBoxCodigoPrenda();
        llenarComboBoxColores();
        llenarComboBoxTalles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerCantidad = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxColor = new javax.swing.JComboBox<>();
        jComboBoxTalle = new javax.swing.JComboBox<>();
        jComboBoxCodigoPrenda = new javax.swing.JComboBox<>();
        jButtonAgregarLineaDeSolicitud = new javax.swing.JButton();
        jButtonGenerarSolicitud = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLineasDeSolicitud = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Cantidad");

        jSpinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9, 1));

        jLabel3.setText("Código");

        jLabel4.setText("Color");

        jLabel5.setText("Talle");

        jButtonAgregarLineaDeSolicitud.setText("Agregar");
        jButtonAgregarLineaDeSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarLineaDeSolicitudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCodigoPrenda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxTalle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(539, 539, 539))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAgregarLineaDeSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCodigoPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAgregarLineaDeSolicitud)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonGenerarSolicitud.setText("Generar Solicitud");
        jButtonGenerarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarSolicitudActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTableLineasDeSolicitud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cantidad", "Prenda", "Color", "Talle"
            }
        ));
        jScrollPane1.setViewportView(jTableLineasDeSolicitud);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setText("Nueva Solicitud");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonGenerarSolicitud)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGenerarSolicitud)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonGenerarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarSolicitudActionPerformed
        GenerarSolicitud();
    }//GEN-LAST:event_jButtonGenerarSolicitudActionPerformed

    private void jButtonAgregarLineaDeSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarLineaDeSolicitudActionPerformed
        String cantidad = getjSpinnerCantidad().getValue().toString();
        String codigo = getjComboBoxCodigoPrenda().getSelectedItem().toString();
        String color = getjComboBoxColor().getSelectedItem().toString();
        String talle = getjComboBoxTalle().getSelectedItem().toString();
        //agrega a la tabla
        this.agregarLineaDeSolicitud(cantidad, codigo, color, talle);
    }//GEN-LAST:event_jButtonAgregarLineaDeSolicitudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaNuevoFormulario().setVisible(true);
            }
        });
    }

    public JComboBox<String> getjComboBoxColor() {
        return jComboBoxColor;
    }

    public JComboBox<String> getjComboBoxTalle() {
        return jComboBoxTalle;
    }

    public JSpinner getjSpinnerCantidad() {
        return jSpinnerCantidad;
    }

    public JComboBox<String> getjComboBoxCodigoPrenda() {
        return jComboBoxCodigoPrenda;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAgregarLineaDeSolicitud;
    private javax.swing.JButton jButtonGenerarSolicitud;
    private javax.swing.JComboBox<String> jComboBoxCodigoPrenda;
    private javax.swing.JComboBox<String> jComboBoxColor;
    private javax.swing.JComboBox<String> jComboBoxTalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerCantidad;
    private javax.swing.JTable jTableLineasDeSolicitud;
    // End of variables declaration//GEN-END:variables
   
    private void GenerarSolicitud() {
        
        //Component frame = null;
        //JOptionPane.showMessageDialog(frame, "Cantidad: " + cantidad + "\nCodigo: " + codigo + "\nColor: " + color + "\nTalle: " + talle);
    }

    public void limpiarListaDeSolicitudes() {
        DefaultTableModel modeloTabla = (DefaultTableModel) jTableLineasDeSolicitud.getModel();
        modeloTabla.setRowCount(0);
    }
    
    private void llenarComboBoxCodigoPrenda() {
        ArrayList<Prenda> prendas = catalogo.inicializarCatalogo();
        for(Prenda prenda : prendas){
            jComboBoxCodigoPrenda.addItem(prenda.getCodigo());
        }
    }
    
    private void llenarComboBoxColores() {
        ArrayList<Color> colores = catalogo.InicializarColores();
        for(Color color : colores){
            jComboBoxColor.addItem(color.getNombreColor());
        }
    }
    
    private void llenarComboBoxTalles(){
        ArrayList<Talle> talles = catalogo.InicializarTalles();
        for(Talle talle : talles){
            jComboBoxTalle.addItem(talle.getNombreTalle());
        }
    }
    
    public Prenda buscarPrenda(String codigo){
        Prenda prendaEncontrada = new Prenda();
        ArrayList<Prenda> prendas = catalogo.inicializarCatalogo();
        for(Prenda prenda : prendas){
            if(prenda.getCodigo() == codigo){
                prendaEncontrada = prenda;
            }
        }
        return prendaEncontrada;
    }
    
    public Talle buscarTalle(String nombreTalle){
        Talle talleEncontrado = new Talle();
        ArrayList<Talle> talles = catalogo.InicializarTalles();
        for(Talle talle : talles){
            if(talle.getNombreTalle() == nombreTalle){
                talleEncontrado = talle;
            }
        }
        return talleEncontrado;
    }
    
    public Color buscarColor(String nombreColor){
        Color colorEncontrado = new Color();
        ArrayList<Color> colores = catalogo.InicializarColores();
        for(Color color: colores){
            if(color.getNombreColor() == nombreColor){
                colorEncontrado = color;
            }
        }
        return colorEncontrado;
    }
    public void agregarLineaDeSolicitud(String cantidad, String codigoPrenda, String color, String talle) {
        DefaultTableModel modeloTabla = (DefaultTableModel) jTableLineasDeSolicitud.getModel();
        modeloTabla.addRow(new Object[] {cantidad, codigoPrenda, color, talle});
        LineaDeSolicitud lineaDeSolicitud = new LineaDeSolicitud(Integer.parseInt(cantidad), buscarPrenda(codigoPrenda), buscarTalle(talle), buscarColor(color));
        lineasDeSolicitud.add(lineaDeSolicitud);
        System.out.println(lineasDeSolicitud.toString());
    }
}
